### ISSUE TITLE
doens't work

### ISSUE THREAD

**Issue by amhooman** [shalldie/a-dance-of-file-and-ice#1]
shows as a blank tab that says "documents"

**Comment by shalldie** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/9987486/161372192-0748574c-b069-4604-a9c4-ebbae4a194d9.png">

It means:
`It's not finished, I'll do it when I'm free.`

...Finally I `gave up`.

Maybe you're interested in this, which is `finished`: https://github.com/shalldie/togame

---

`a-dance-of-fire-and-ice` is a test project, you can see the progress by the steps:

```bash
npm i
npm run dev
```

**Comment by amhooman** [comment]
thanks!
